// Wherever We Are
// Laptop orchestra piece

// Comment out desired screen resolution for projection

// ===========
// 1024 x 768
// ===========

~screenWidth = 1024;
~screenHeight = 768;
~margin = 2@0;
~gap = 8@10;
~bounds = 40@40;
~fontSize = 42;



// ===========
// 1366 x 768
// ===========

/*
~screenWidth = 1366;
~screenHeight = 768;
~margin = 0@0;
~gap = 9@18;
~bounds = 40@50;
~fontSize = 52;
*/